### ISSUE TITLE
Using own data

### ISSUE THREAD

**Issue by ajaysurya1221** [declare-lab/ASTE-RL#1]
Loading data...
{'NEU': 2442, 'POS': 738, 'NEG': 1390}
['NEU', 'POS', 'NEG']
#train_data: 2277
#dev_data: 587
#test_data: 777
Starting training service, overall process number:  1
Train epoch 0 ...
Process  0  start service.
Train batch 0 : F1= 0.9047619047619047 , time= 6.834511995315552
Train batch 50 : F1= 0.9473684210526316 , time= 5.462005853652954
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/content/ASTE-RL/TrainProcess.py", line 138, in worker
    acc, cnt, tot, loss = workProcess(model, datas, sample_round, mode, device, sentiments, test)
  File "/content/ASTE-RL/TrainProcess.py", line 25, in workProcess
    preoptions, pre_aspect_actions, pre_opinion_actions, device, sentiments)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/ASTE-RL/Model.py", line 156, in forward
    posvs[y], bot_bert_cls, self.opinionvector(actionb), wordinbot[y], \
IndexError: index 96 is out of bounds for dimension 0 with size 96

Please Help.

**Comment by jurys22** [comment]
I have not used this repo yet, just going to use it soon. From the error it seems an out of bound of the data - word vector it is processing.

**Comment by jurys22** [comment]
Question: how fast for it was going from the start to process Process 2?
